### ISSUE TITLE
Checking python environment

### ISSUE THREAD

**Issue by lmolnar42** [spacetelescope/aas229_workshop#8]
I cloned the repository with git (per step 1) and installed anaconda (per step 2a), but the environment check came up with a number of omissions and outdated versions.  I copy the message below.

Lawrences-MacBook-Pro:aas229_workshop Larry$ python check_env.py
Error: ginga version 2.6.1 or later is required, you have version 2.5.20161005204600
Error: stginga version 0.1.3 or later is required, you have version 0.1.2.dev197
Found matplotlib 1.5.3
Error: Failed import: No module named 'gwcs'
Error: Failed import: No module named 'astroquery'
Found skimage 0.12.3
Error: Failed import: No module named 'specviz'
Found astropy 1.2.1
Found pandas 0.18.1
Found scipy 0.18.1
/Users/Larry/astroconda/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/Users/Larry/astroconda/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "check_env.py", line 61, in <module>
    errors.append(check_package(package_name, minimum_version=min_version))
  File "check_env.py", line 29, in check_package
    LooseVersion(str(minimum_version))):
  File "/Users/Larry/astroconda/lib/python3.5/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/Users/Larry/astroconda/lib/python3.5/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: unorderable types: str() < int()

**Comment by sosey** [comment]
After installing Anaconda in 2a, did you go on to 2b and create an environment for the workshop using the environment file? If not, try that and  then run the check script again. Let me know if this works for you.

**Comment by sosey** [comment]
ah - if you used the shell installer script in 2a, it might well be this is behind in the versions, if that is the case then I will notify you when the installer is updated. An easy fix is to do above, create a new anaconda ennvironment and use the 2b instructions instead.

**Comment by lmolnar42** [comment]
In the installation and setup instructions it says not to run step 2b if you have run step 2a, so I did not at first.  However, now I have run all of step 2b and my python environment check comes up clean.

The line saying not to run 2b should be changed.

Thanks for your help.  I will see you Tuesday morning.

**Comment by sosey** [comment]
I'll make that more clear. I think your original try should have succeeded as well, but the installers might be out of date. Glad it's working for you now...cheers

**Comment by sosey** [comment]
@jhunkeler will you add the installers with updated versions to the repo when you are able?

**Comment by pllim** [comment]
For now, I added some text to make **Step 2b** a bit clearer.

**Comment by astrolf** [comment]
I got similar problem, as below:

Found matplotlib 2.0.0rc2
Found photutils 0.3
Found astroquery 0.3.4
Found notebook 4.3.1
Error: Failed import: No module named 'specviz'
Error: Failed import: No module named 'gwcs'
Error: Failed import: No module named 'imexam'
Found skimage 0.12.3
Error: Failed import: No module named 'ginga'
Error: Failed import: No module named 'stginga'
Found pandas 0.19.2
Found astropy 1.3
Found scipy 0.18.1
Found glue 0.9.1
Found IPython 5.1.0
Found numpy 1.11.3

There are errors that you must resolve before running the tutorials.
